### ISSUE TITLE
How about the performance?

### ISSUE THREAD

**Issue by xiaoiker** [neeraj3029/Ne2Ne-Image-Denoising#1]
Hi,
Thanks for the codes. Can you get the performance reported in the paper? 

BR.

**Comment by neeraj3029** [comment]
I couldn't really, as my training dataset was just 300 images large. While the authors trained the model on ImageNet validation (50k Images) and fine-tuned on smaller datasets

**Comment by xiaoiker** [comment]
Got that, thanks!
