### ISSUE TITLE
training with Raw-image 

### ISSUE THREAD

**Issue by whohyx** [neeraj3029/Ne2Ne-Image-Denoising#2]
hi, thank for your contribution. 
in this paper ,the author said that using the SIDD to train for real-world denoising experiments in raw- RGB space .But how ? How to train raw-RGB image ,it is different from training with image.PNG or Image.jpg . 
It means that convert raw-RGB image to RGB image and then train with RGB  imgae？
Looking forward to your reply.

**Comment by neeraj3029** [comment]
Hi @whohyx , 

From what I understood from the homepage of SIDD dataset, the raw-RGB images are available in .mat extension, which essentially belongs to the MATLAB family.

However, s-RGB noisy images are available in .png format, which might be easier to handle imo.

Please refer to the following link: https://www.kenrockwell.com/tech/adobe-rgb.htm

**Comment by neeraj3029** [comment]
感谢您的贡献
